{
 "title": "Proxmox",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "database", "label": "Database", "query": "influxdb" },
   { "name": "storage", "query": "ceph" },
   {
    "name": "interface",
    "query": "SHOW TAG VALUES FROM nics WITH key=\"instance\""
   },
   {
    "name": "hostname",
    "label": "node",
    "query": "SHOW TAG VALUES FROM system WITH key=\"nodename\""
   },
   {
    "name": "hostname_all",
    "query": "SHOW TAG VALUES FROM system WITH key=\"nodename\""
   },
   {
    "name": "count_nodes",
    "query": "SELECT COUNT(count) FROM ( SELECT COUNT(\"active\") FROM \"system\" WHERE $timeFilter GROUP BY \"nodename\")"
   }
  ]
 },
 "panels": [
  { "title": "Cluster Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Number of Nodes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$count_nodes", "type": "math" }
   ]
  },
  {
   "title": "Nodes",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "alias": "$host",
     "groupBy": [
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "object" ], "type": "tag" }
     ],
     "limit": "1",
     "measurement": "system",
     "query": "SELECT last(\"cpu\") * 100 FROM \"cpustat\" WHERE $timeFilter GROUP BY \"host\" fill(null) LIMIT 1",
     "select": [
      [
       { "params": [ "uptime" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Uptime" ], "type": "alias" }
      ],
      [
       { "params": [ "cpu" ], "type": "field" },
       { "params": [ "Cpu %" ], "type": "alias" }
      ],
      [
       { "params": [ "cpus" ], "type": "field" },
       { "params": [ "Cpus" ], "type": "alias" }
      ],
      [
       { "params": [ "mem" ], "type": "field" },
       { "params": [ "RAM" ], "type": "alias" }
      ],
      [
       { "params": [ "disk" ], "type": "field" },
       { "params": [ "Disk" ], "type": "alias" }
      ],
      [
       { "params": [ "status" ], "type": "field" },
       { "params": [ "Status" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "nodename", "operator": "=~", "value": "/^$hostname$/" }
     ]
    },
    {
     "alias": "$host",
     "query": "SELECT mean(\"memused\")/mean(\"memtotal\")*100 FROM \"memory\" GROUP BY host fill(null) LIMIT 1"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "${A} / $count_nodes", "type": "math" }
   ]
  },
  {
   "title": "RAM usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "memory",
     "query": "SELECT mean(\"memused\")/mean(\"memtotal\")*100 FROM \"memory\" WHERE $timeFilter fill(null) ",
     "select": [
      [
       { "params": [ "memused" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Storage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "query": "SELECT mean(\"used\")/mean(\"total\") FROM \"system\" WHERE $timeFilter AND (\"host\" = '$storage') fill(null)",
     "select": [
      [
       { "params": [ "used" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "dir" },
      { "condition": "AND", "key": "nodename", "operator": "=", "value": "amvita" }
     ]
    }
   ]
  },
  {
   "title": "Total VMs/CTs",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "object" ], "type": "tag" }
     ],
     "limit": "1",
     "measurement": "system",
     "query": "SELECT last(\"status\") FROM \"system\" WHERE $timeFilter AND (\"nodename\" =~ /^$hostname_all$/) AND $timeFilter GROUP BY \"host\" LIMIT 1",
     "select": [
      [
       { "params": [ "uptime" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Uptime" ], "type": "alias" }
      ],
      [
       { "params": [ "cpu" ], "type": "field" },
       { "params": [ "Cpu %" ], "type": "alias" }
      ],
      [
       { "params": [ "cpus" ], "type": "field" },
       { "params": [ "Cpus" ], "type": "alias" }
      ],
      [
       { "params": [ "mem" ], "type": "field" },
       { "params": [ "RAM" ], "type": "alias" }
      ],
      [
       { "params": [ "disk" ], "type": "field" },
       { "params": [ "Disk" ], "type": "alias" }
      ],
      [
       { "params": [ "status" ], "type": "field" },
       { "params": [ "Status" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "nodename", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 8 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "object" ], "type": "tag" }
     ],
     "limit": "1",
     "measurement": "system",
     "query": "SELECT last(\"status\") FROM \"system\" WHERE $timeFilter AND (\"object\" =~ /^qemu$/) AND (\"nodename\" =~ /^$hostname_all$/) AND $timeFilter GROUP BY \"host\" LIMIT 1",
     "select": [
      [
       { "params": [ "uptime" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Uptime" ], "type": "alias" }
      ],
      [
       { "params": [ "cpu" ], "type": "field" },
       { "params": [ "Cpu %" ], "type": "alias" }
      ],
      [
       { "params": [ "cpus" ], "type": "field" },
       { "params": [ "Cpus" ], "type": "alias" }
      ],
      [
       { "params": [ "mem" ], "type": "field" },
       { "params": [ "RAM" ], "type": "alias" }
      ],
      [
       { "params": [ "disk" ], "type": "field" },
       { "params": [ "Disk" ], "type": "alias" }
      ],
      [
       { "params": [ "status" ], "type": "field" },
       { "params": [ "Status" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "nodename", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 8 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "object" ], "type": "tag" }
     ],
     "limit": "1",
     "measurement": "system",
     "query": "SELECT last(\"status\") FROM \"system\" WHERE $timeFilter AND (\"object\" =~ /^lxc$/) AND (\"nodename\" =~ /^$hostname_all$/) AND $timeFilter GROUP BY \"host\" LIMIT 1",
     "select": [
      [
       { "params": [ "uptime" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Uptime" ], "type": "alias" }
      ],
      [
       { "params": [ "cpu" ], "type": "field" },
       { "params": [ "Cpu %" ], "type": "alias" }
      ],
      [
       { "params": [ "cpus" ], "type": "field" },
       { "params": [ "Cpus" ], "type": "alias" }
      ],
      [
       { "params": [ "mem" ], "type": "field" },
       { "params": [ "RAM" ], "type": "alias" }
      ],
      [
       { "params": [ "disk" ], "type": "field" },
       { "params": [ "Disk" ], "type": "alias" }
      ],
      [
       { "params": [ "status" ], "type": "field" },
       { "params": [ "Status" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "nodename", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 11 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "object" ], "type": "tag" }
     ],
     "limit": "1",
     "measurement": "system",
     "query": "SELECT last(\"status\") FROM \"system\" WHERE $timeFilter AND (\"object\" =~ /^qemu$/) AND (\"nodename\" =~ /^$hostname_all$/) AND $timeFilter GROUP BY \"host\" LIMIT 1",
     "select": [
      [
       { "params": [ "uptime" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Uptime" ], "type": "alias" }
      ],
      [
       { "params": [ "cpu" ], "type": "field" },
       { "params": [ "Cpu %" ], "type": "alias" }
      ],
      [
       { "params": [ "cpus" ], "type": "field" },
       { "params": [ "Cpus" ], "type": "alias" }
      ],
      [
       { "params": [ "mem" ], "type": "field" },
       { "params": [ "RAM" ], "type": "alias" }
      ],
      [
       { "params": [ "disk" ], "type": "field" },
       { "params": [ "Disk" ], "type": "alias" }
      ],
      [
       { "params": [ "status" ], "type": "field" },
       { "params": [ "Status" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "nodename", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 11 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "object" ], "type": "tag" }
     ],
     "limit": "1",
     "measurement": "system",
     "query": "SELECT last(\"status\") FROM \"system\" WHERE $timeFilter AND (\"object\" =~ /^lxc$/) AND (\"nodename\" =~ /^$hostname_all$/) AND $timeFilter GROUP BY \"host\" LIMIT 1",
     "select": [
      [
       { "params": [ "uptime" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Uptime" ], "type": "alias" }
      ],
      [
       { "params": [ "cpu" ], "type": "field" },
       { "params": [ "Cpu %" ], "type": "alias" }
      ],
      [
       { "params": [ "cpus" ], "type": "field" },
       { "params": [ "Cpus" ], "type": "alias" }
      ],
      [
       { "params": [ "mem" ], "type": "field" },
       { "params": [ "RAM" ], "type": "alias" }
      ],
      [
       { "params": [ "disk" ], "type": "field" },
       { "params": [ "Disk" ], "type": "alias" }
      ],
      [
       { "params": [ "status" ], "type": "field" },
       { "params": [ "Status" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "nodename", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "Node Info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "query": "SELECT last(\"uptime\") FROM \"system\" WHERE $timeFilter AND (\"host\" =~ /^$hostname$/)\n",
     "select": [
      [
       { "params": [ "uptime" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "nodename", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "cpustat",
     "query": "SELECT last(\"cpu\") FROM \"cpustat\" WHERE $timeFilter AND (\"host\" =~ /^$hostname$/)",
     "select": [
      [
       { "params": [ "cpu" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "RAM usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "memory",
     "query": "SELECT mean(\"memused\")/mean(\"memtotal\")*100 FROM \"memory\" WHERE $timeFilter AND (\"host\" =~ /^$hostname$/) GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "memused" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Directory",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "query": "SELECT mean(\"used\")/mean(\"total\") FROM \"system\" WHERE (\"type\" = 'dir' AND \"nodename\" =~ /^$hostname$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "used" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "dir" },
      { "condition": "AND", "key": "nodename", "operator": "=", "value": "amvita" }
     ]
    }
   ]
  },
  {
   "title": "RAM Used",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "gbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "memory",
     "query": "SELECT mean(\"memused\") / 1073741824 FROM \"memory\" WHERE $timeFilter AND (\"host\" =~ /^$hostname$/) GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "memused" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "/ 1073741824" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total RAM",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "memory",
     "query": "SELECT mean(\"memtotal\") FROM \"memory\" WHERE $timeFilter AND (\"host\" =~ /^$hostname$/) GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "memtotal" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "RAM Available",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "memory",
     "query": "SELECT mean(\"memfree\") FROM \"memory\" WHERE $timeFilter AND (\"host\" =~ /^$hostname$/) GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "memfree" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "VM / CT",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "object" ], "type": "tag" }
     ],
     "limit": "1",
     "measurement": "system",
     "query": "SELECT last(\"uptime\") AS \"Uptime\", \"cpu\" AS \"Cpu %\", \"cpus\" AS \"Cpus\", \"mem\" AS \"RAM\", \"disk\" AS \"Disk\", \"status\" AS \"Status\" FROM \"system\" WHERE (\"nodename\" =~ /^$hostname$/) AND $timeFilter GROUP BY \"host\", \"object\" LIMIT 1",
     "select": [
      [
       { "params": [ "uptime" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Uptime" ], "type": "alias" }
      ],
      [
       { "params": [ "cpu" ], "type": "field" },
       { "params": [ "Cpu %" ], "type": "alias" }
      ],
      [
       { "params": [ "cpus" ], "type": "field" },
       { "params": [ "Cpus" ], "type": "alias" }
      ],
      [
       { "params": [ "mem" ], "type": "field" },
       { "params": [ "RAM" ], "type": "alias" }
      ],
      [
       { "params": [ "disk" ], "type": "field" },
       { "params": [ "Disk" ], "type": "alias" }
      ],
      [
       { "params": [ "status" ], "type": "field" },
       { "params": [ "Status" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "nodename", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "Cpu Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "alias": "CPU Usage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpustat",
     "query": "SELECT mean(\"cpu\") FROM \"cpustat\" WHERE $timeFilter AND (\"host\" =~ /^$hostname$/) GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "cpu" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "RAM Usage (%)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "ram usage (%)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "memory",
     "query": "SELECT mean(\"memused\")/mean(\"memtotal\")*100 FROM \"memory\" WHERE $timeFilter AND (\"host\" =~ /^$hostname$/) GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "memused" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "RAM Usage (GiB)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "memory",
     "query": "SELECT mean(\"memtotal\") AS \"total\", mean(\"memused\") AS \"used\", mean(\"memfree\") AS \"free\" FROM \"memory\" WHERE $timeFilter AND (\"host\" =~ /^$hostname$/) GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "memtotal" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "total" ], "type": "alias" }
      ],
      [
       { "params": [ "memused" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "used" ], "type": "alias" }
      ],
      [
       { "params": [ "memfree" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "free" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Traffic In / Out",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nics",
     "query": "SELECT non_negative_derivative(last(\"receive\"), 1s) *8 AS \"Download\", non_negative_derivative(last(\"transmit\"), 1s) *8 AS \"Upload\" FROM \"nics\" WHERE (\"host\" =~ /^$hostname$/ AND \"instance\" =~ /^$interfaces$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "receive" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" },
       { "params": [ "Download" ], "type": "alias" }
      ],
      [
       { "params": [ "transmit" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" },
       { "params": [ "Upload" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$interfaces$/" }
     ]
    }
   ]
  },
  {
   "title": "Virtual Machine / Linux LXC Container",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Usage By CT / VM",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "query": "SELECT mean(\"cpu\") FROM \"system\" WHERE (\"nodename\" =~ /^$hostname$/) AND $timeFilter GROUP BY time($__interval), \"host\" fill(null)",
     "select": [
      [
       { "params": [ "cpu" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "nodename", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "Memory Usage By CT / VM",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "query": "SELECT mean(\"mem\") FROM \"system\" WHERE (\"nodename\" =~ /^$hostname$/) AND $timeFilter GROUP BY time($__interval), \"host\" fill(null)",
     "select": [
      [
       { "params": [ "mem" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "nodename", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "Traffic In By CT / VM",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "query": "SELECT non_negative_derivative(last(\"netin\"), 1s) *8 FROM \"system\" WHERE (\"nodename\" =~ /^$hostname$/) AND $timeFilter GROUP BY time($__interval), \"host\" fill(null)",
     "select": [
      [
       { "params": [ "netin" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "nodename", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "Traffic Out By CT / VM",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "query": "SELECT non_negative_derivative(last(\"netout\"), 1s) *8 FROM \"system\" WHERE (\"nodename\" =~ /^$hostname$/) AND $timeFilter GROUP BY time($__interval), \"host\" fill(null)",
     "select": [
      [
       { "params": [ "netout" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "nodename", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  }
 ]
}